config/routes.rb
Rails.application.routes.draw do
  root 'charts#index'
  
  resources :artists do
    resources :songs, only: [:edit, :new, :create, :destroy, :update]
  end

  patch '/chart/:id/song/:song_id', to: 'charts#add_song_to_chart', as: "song_to_chart"
	delete 'remove_billboard_song/:id/:song_id', to: 'charts#remove_song_from_chart', as: 'remove_song_from_chart'
  
  resources :charts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :chart, optional: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]
  
  def index
    @artists = Artist.order(:name)
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render partial: "form"
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render partial: "form"
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :update, :edit, :destroy, :add_song_to_chart, :remove_song_from_chart]
  before_action :set_song, only: [:add_song_to_chart, :remove_song_from_chart]
  
  def index
    @charts = Chart.all
  end

  def show
    @artists = Artist.all
  end

  def new
    @chart = Chart.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @chart = Chart.new(chart_params)
    if @chart.save
      redirect_to chart_path(@chart)
    else
      render partial: "form"
    end
  end

  def update
    if @chart.update(chart_params)
      redirect_to chart_path(@chart)
    else
      render partial: "form"
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  def add_song_to_chart
    @chart.songs << @song
    redirect_to chart_path(@chart)
  end

  def remove_song_from_chart
    Song.find(params[:song_id]).update(chart_id: nil)
    redirect_to chart_path(@chart)
  end

  private
    def set_chart
      @chart = Chart.find(params[:id])
    end

    def set_song
      @song = Song.find(params[:song_id])
    end 

    def chart_params
      params.require(:chart).permit(:name)
    end
end

app/controllers/songs_controller.rb
require 'pry'

class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only:[:edit, :update, :destroy, :remove_song_from_chart]
  
  def edit
  end

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to artist_path(@song.artist)
    else
      render :edit
    end
  end

  def destroy
    artist = @song.artist
    @song.destroy
    redirect_to artist_path(artist)
  end

  private
    def set_artist 
      @artist = Artist.find(params[:artist_id])
    end

    def set_song 
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist, :chart)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<header class="container">
<h1>View All Artists</h1>
</header>
<section class="container">
<table class="table song_table">
  <thead>
    <tr><th>Artist Name</th><th></th><th></th><th></th></tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to "View/Add Songs", artist %></td>
        <td><%= link_to "Edit Artist", edit_artist_path(artist) %></td>
        <td><%= link_to "Delete", artist_path(artist), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add New Artist", new_artist_path %>
<br />
<%= link_to "Back To Charts", charts_path %>
</section>

app/views/artists/show.html.erb
<header class="container">
<h1><%= @artist.name %></h1>
</header>
<section class="container">
<h3>Songs</h3>
<table class="table song_table">
  <thead>
    <tr><th>Title</th><th>Edit</th><th>Delete</th>
  </thead>
  <tbody> 
    <% @artist.songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= link_to "Edit", edit_artist_song_path(@artist, song) %></td>
        <td><%= link_to "Delete", artist_song_path(@artist, song), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>
<%= link_to "Add Song", new_artist_song_path(@artist) %>
<br />
<%= link_to "Back To Artists", artists_path%>
</section>

app/views/charts/_form.html.erb
<h1><%= @chart.id ? 'Edit Chart' : 'Create Chart' %></h1>
<hr />
<%= form_for @chart do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/charts/index.html.erb
<section class="container" id="front_page_box">
<h1>Welcome To Billboard!</h1>
<table class="table front_page_table">
  <thead>
    <tr><th>Chart Name</th><th></th><th></th><th></th></tr>
  </thead>
  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= chart.name %></td>
        <td><%= link_to "View", chart %></td>
        <td><%= link_to "Edit", edit_chart_path(chart) %></td>
        <td><%= link_to "Delete", chart_path(chart), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add New Chart", new_chart_path %>
<%= link_to "View & Add Artists", artists_path%>
</section>

app/views/charts/show.html.erb
<header class="container">
<h1><%= @chart.name %></h1>
</header>

<section class="container">
  <div class="row">
    <div class="col-sm">
    <h3>Songs On Chart</h3>
      <table class="table song_table">
        <thead>
          <tr><th>Title</th><th>Artist</th><th></th><th></th></tr>
        </thead>
        <tbody>
          <% @chart.songs.each do |song| %>
            <tr>
              <td><%= song.title %></td>
              <td><%= song.artist.name %></td>
              <td><%= link_to "Edit", edit_artist_song_path(song.artist, song)%></td>
              <td><%= link_to "Remove", remove_song_from_chart_path(@chart, song), method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= link_to "Back To Charts", charts_path %>
    </div>

    <div class="col-sm">
      <h3> Click Songs to add </h3>
      <% @artists.each do |artist| %>
        <h5><%= artist.name %></h5>
        <table class="table song_table">
          <tbody>
          <% artist.songs.each do |song| %>
          <% if song.chart != @chart %>
            <tr>
              <td><%= link_to song.title, song_to_chart_path(@chart, song), method: :patch %></td>
              <td><%= link_to "Edit Song",edit_artist_song_path(artist, song)%></td>
            </tr>
          <% end %>
        <% end %>
          </tbody>
        </table>
      <% end %>
    <%= link_to "Add New Artist", new_artist_path %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.1.erb
<h1>Add Song for <%= @artist.name %></h1>
<hr />
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true%>
 
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/new.html.erb
<h1>Add Song for <%= @artist.name %></h1>
  <%= form_for [@artist, @song] do |f| %>
   <%= f.text_field :title, placeholder: "Song Title", required: true%>
   <%= f.submit %>
  <% end %>